commit 8b4c0009313f3d42e2540e3e1f776097dd0db73d Author: Vishal Thanki <vishalthanki@gmail.com> Date:   Sat Mar 19 11:41:01 2016 +0100
    rt2x00usb: Use usb anchor to manage URB

    With current driver, it is observed that a URB is not
    completed while the USB disconnect is initiated. Due to
    that, the URB completion handler is trying to access
    the resource which was freed as a part of USB disconnect.
    Managing the URBs with anchor will make sure that all
    the URBs are handled gracefully before device gets
    disconnected.

    Signed-off-by: Vishal Thanki <vishalthanki@gmail.com>
    Acked-by: Stanislaw Gruszka <sgruszka@redhat.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

commit f36f299068794ffc5026f25b6a1b3ed615ea832d
Author: Anthony Wong <anthony.wong@ubuntu.com>
Date:   Tue Feb 23 23:09:22 2016 +0800

    rt2x00: add new rt2800usb device Buffalo WLI-UC-G450

    Add USB ID 0411:01fd for Buffalo WLI-UC-G450 wireless adapter,
    RT chipset 3593

    Signed-off-by: Anthony Wong <anthony.wong@ubuntu.com>
    Cc: stable@vger.kernel.org
    Acked-by: Stanislaw Gruszka <sgruszka@redhat.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

commit 9cc3fdc86c6006bae878da6d2d14c1633064a12f
Author: One Thousand Gnomes <gnomes@lxorguk.ukuu.org.uk>
Date:   Mon Feb 15 19:04:56 2016 +0000

    rt2x00: unterminated strlen of user data

    The buffer needs to be zero terminated in case the user data is not.
    Otherwise we run off the end of the buffer.

    Signed-off-by: Alan Cox <alan@linux.intel.com>
    Reviewed-by: Julian Calaby <julian.calaby@gmail.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

commit d67703fcede6696667218d29f86b4ee6ae618de6
Merge: 4ec6207 50ee738
Author: David S. Miller <davem@davemloft.net>
Date:   Tue Mar 1 17:02:30 2016 -0500

    Merge tag 'mac80211-next-for-davem-2016-02-26' of git://git.kernel.org/pub/scm/linux/kernel/git/jberg/mac80211-next

    Johannes Berg says:

    ====================
    Here's another round of updates for -next:
     * big A-MSDU RX performance improvement (avoid linearize of paged RX)
     * rfkill changes: cleanups, documentation, platform properties
     * basic PBSS support in cfg80211
     * MU-MIMO action frame processing support
     * BlockAck reordering & duplicate detection offload support
     * various cleanups & little fixes
    ====================

    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 6cd21d79419c154a73be6fa31bc1a1f42ffd6815
Merge: 27090cb 11e7082
Author: David S. Miller <davem@davemloft.net>
Date:   Tue Feb 16 20:38:29 2016 -0500

    Merge tag 'wireless-drivers-next-for-davem-2016-02-12' of git://git.kernel.org/pub/scm/linux/kernel/git/kvalo/wireless-drivers-next

    Kalle Valo says:

    ====================
    Major changes:

    wl12xx

    * add device tree support for SPI

    mwifiex

    * add debugfs file to read chip information
    * add MSIx support for newer pcie chipsets (8997 onwards)
    * add schedule scan support
    * add WoWLAN net-detect support
    * firmware dump support for w8997 chipset

    iwlwifi

    * continue the work on multiple Rx queues
    * add support for beacon storing used in low power states
    * use the regular firmware image of WoWLAN
    * fix 8000 devices for Big Endian machines
    * more firmware debug hooks
    * add support for P2P Client snoozing
    * make the beacon filtering for AP mode configurable
    * fix transmit queues overflow with LSO

    libertas

    * add support for setting power save via cfg80211
    ====================

    Signed-off-by: David S. Miller <davem@davemloft.net>

commit 5b451715e94d43fdb8f3cca67d1ec72184f294f9
Author: Paul Mcquade <paulmcquad@gmail.com>
Date:   Sat Oct 17 22:11:23 2015 +0100

    net: wireless: rt2x00: Space Required

    Space needed before open parenthesis

    Signed-off-by: Paul McQuade <paulmcquad@gmail.com>
    Acked-by: Helmut Schaa <helmut.schaa@googlemail.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

commit b2cc2dd8ebb885ad1b2ee4c5d35b40d98db211fa
Author: Paul Mcquade <paulmcquad@gmail.com>
Date:   Sat Oct 17 22:06:43 2015 +0100

    net: wireless: rt2x00: Space issue

    Removed empty spaces before/after parenthesis

    Signed-off-by: Paul McQuade <paulmcquad@gmail.com>
    Acked-by: Helmut Schaa <helmut.schaa@googlemail.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

commit ac2b335e7149e7dd0c8dcbb2b158a17b78c480a1
Author: Paul Mcquade <paulmcquad@gmail.com>
Date:   Sat Oct 17 21:04:39 2015 +0100

    net: wireless: rt2x00: Fixed Spacing issues

    Removed empty spaces before/after parenthesis

    Signed-off-by: Paul McQuade <paulmcquad@gmail.com>
    Acked-by: Helmut Schaa <helmut.schaa@googlemail.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

commit 262c741e0825b29447a9e53b6582afd6b14c3706
Author: Eli Cooper <elicooper@gmx.com>
Date:   Mon Jan 18 19:30:19 2016 +0800

    rt2x00: fix monitor mode regression

    Since commit df1404650ccb ("mac80211: remove support for IFF_PROMISC")
    monitor mode for rt2x00 has been made effectively useless because the
    hardware filter is configured to drop packets whose intended recipient is
    not the device, regardless of the presence of monitor mode interfaces.

    This patch fixes this regression by adding explicit monitor mode support,
    and by configuring the hardware filter accordingly.

    Signed-off-by: Eli Cooper <elicooper@gmx.com>
    Acked-by: Stanislaw Gruszka <sgruszka@redhat.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

commit 50ea05efaf3bed7dd34bcc2635a8b3f53bd0ccc1
Author: Sara Sharon <sarasharon1@gmail.com>
Date:   Wed Dec 30 16:06:04 2015 +0200

    mac80211: pass block ack session timeout to to driver

    Currently mac80211 does not inform the driver of the session
    block ack timeout when starting a rx aggregation session.
    Drivers that manage the reorder buffer need to know this
    parameter.
    Seeing that there are now too many arguments for the
    drv_ampdu_action() function, wrap them inside a structure.

    Signed-off-by: Sara Sharon <sara.sharon@intel.com>
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

commit 7683fe016c010a20b5f2d88b7d8dad198506f5f7
Author: Jia-Ju Bai <baijiaju1990@163.com>
Date:   Mon Jan 4 15:55:38 2016 +0800

    rt2x00pci: Disable memory-write-invalidate when the driver exits

    The driver calls pci_set_mwi to enable memory-write-invalidate when it
    is initialized, but does not call pci_clear_mwi when it is removed. Many
    other drivers calls pci_clear_mwi when pci_set_mwi is called, such as
    r8169, 8139cp and e1000.

    This patch adds pci_clear_mwi in error handling and removal procedure,
    which can fix the problem.

    Signed-off-by: Jia-Ju Bai <baijiaju1990@163.com>
    Acked-by: Helmut Schaa <helmut.schaa@googlemail.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

commit 952348a5f88b92e412f3e490fb83acc17e68d85c
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Thu Nov 26 14:55:23 2015 +0300

    rt2x00: type bug in _rt2500usb_register_read()

    This code causes a static checker bug.

    drivers/net/wireless/ralink/rt2x00/rt2500usb.c:232 _rt2500usb_register_read()
    warn: passing casted pointer 'value' to 'rt2500usb_register_read()' 32 vs 16.

    If the low 16 bits were initialized to zero then this code would only be
    a problem on big endian systems.  But in this case this is case the low
    16 bits are never initialized.  This is called from a function which is
    created using a macro:

    RT2X00DEBUGFS_OPS(csr, "0x%.8x\n", u32);

    We end up copying uninitialized data to the user which is bogus and an
    information leak.

    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Acked-by: Stanislaw Gruszka <sgruszka@redhat.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

commit 33aca94d797d7a8b6b4911ba02060c4fa9a0c47d
Author: Kalle Valo <kvalo@codeaurora.org>
Date:   Wed Nov 18 10:18:44 2015 +0200

    rt2x00: move under ralink vendor directory

    Part of reorganising wireless drivers directory and Kconfig.

    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>